---
all:
  hosts:
    sonar-01:
      ansible_host: 192.168.67.15
  children:
    sonarqube:
      hosts:
        sonar-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: alexsys
