---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.38.240
    jenkins-agent-01:
      ansible_host: 158.160.55.76
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: alexsys