services:
  postgres:
    image: ${JIRA_POSTGRES_IMAGE_TAG}
    volumes:
      - jira-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${JIRA_DB_NAME}
      POSTGRES_USER: ${JIRA_DB_USER}
      POSTGRES_PASSWORD: ${JIRA_DB_PASSWORD}
    restart: unless-stopped

  jira:
    image: atlassian/jira-software
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira
    environment:
      ATL_DB_TYPE: postgres72
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: ${JIRA_DB_USER}
      ATL_JDBC_PASSWORD: ${JIRA_DB_PASSWORD}
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/${JIRA_DB_NAME}
volumes:
  jira-postgres:
  jiraVolume: